"""
Define EpisodeStep (transition), Trajectory (sequence of EpisodeStep),
TrajectoryGroup (batch of Trajectory)
"""

from typing import Any

from pydantic import BaseModel


def compute_returns_with_last_value(
    rewards: list[float],
    discount_factor: float = 0.9,
    dones: list[bool] | None = None,
    last_value: float = 0.0,
) -> list[float]:
    """
    Compute returns from rewards with last value
    - Applied over a single rollout
    """
    returns: list[float] = [0.0 for _ in range(len(rewards))]
    _return = last_value
    for t in reversed(range(len(rewards))):
        mask = not dones[t] if dones is not None else 1
        _return = rewards[t] + discount_factor * _return * mask
        returns[t] = _return
    return returns


class EpisodeStep(BaseModel):
    """
    Single episode step, i.e., a transition between two states
    -> Note that tools is optional, but should be saved if available

    MZ 3/28/26 NOTE: Consider renaming:
    - (state, action, next_obs, current_state, final_outcome) to
      (state_msgs, action_msg, next_obs_msgs, current_state_msgs, final_outcome_msgs)
    """

    state: list[dict[str, Any]]
    action: dict[str, Any]
    next_obs: list[dict[str, Any]]

    state_action_tokens: list[int]
    state_len: int
    old_logprobs: list[float]
    temperature: float

    reward: float
    done: bool
    truncated: bool
    timestep: int
    try_step: int

    batch_id: int
    sample_id: int
    generation_id: int
    split: str
    user_id: str = "user"  # for personalization

    return_: float = -2
    advantage: float = -2
    return_is_computed: bool = False
    advantage_is_computed: bool = False
    constant_reward_group: bool = False

    # Store all returns and advantages up to this step
    state_returns: list[float] = []
    state_advantages: list[float] = []
    trajectory_returns: list[float] = []
    trajectory_advantages: list[float] = []

    # Other sample metadata
    system_prompt: str | None = None
    tools: list[dict[str, Any]] | None = None
    answer: str | list[str] | None = None  # str for single-turn, list[str] for multi-turn
    task_prompt: str | None = None         # e.g., the first user message
    default_context: list[dict[str, Any]] | None = None

    # Prior trajectory metadata
    current_state: list[dict[str, Any]] = []
    final_outcome: list[dict[str, Any]] = []
    prior_context: list[dict[str, Any]] | list[str] = []
    prior_rewards: list[float] = []
    prior_returns: list[float] = []
    prior_advantages: list[float] = []
    # Store reflections
    # prior_reflections: list[str] = []  # should be careful, but keep track of past reflections for each try (only used for attn-based reflection)
    prior_reflection: str | None = None

    # Generated state metadata
    # -> We may ask model to summarize or re-generate its state into a shorter form
    #    in which case we should store the full state here
    full_state: list[dict[str, Any]] | None = None
    last_state_act_obs: list[dict[str, Any]] | None = None

    # Retrieval metadata
    is_train: bool = True
    is_icl: bool = False
    is_icl_reverse: bool = False

    # Maybe filter on complete generations
    is_complete: bool = True

    # Flat scalar metrics from the env step's info (e.g. eval env: task_completion,
    # task_personalization, num_respond_user). Empty for envs that don't set them.
    # The Trajectory surfaces the last step's metrics for wandb logging.
    metrics: dict[str, float] = {}

    def model_post_init(self, __context: Any) -> None:
        """Default current_state to state if not provided"""
        self.current_state = self.current_state or self.state
        self.full_state = self.full_state or self.state


class Trajectory:
    """
    Sequence of EpisodeStep or StateActionSample,
    generated by a complete rollout or sourced from a dataset
    """

    def __init__(
        self,
        episode_steps: list[EpisodeStep],
        try_step: int,
        discount_factor: float,
        final_reward: float,
        last_value: float = 0.0,
    ) -> None:
        self.episode_steps = episode_steps
        self.try_step = try_step
        self.discount_factor = discount_factor
        self.final_reward = final_reward
        self.last_value = last_value

        self.returns = self.compute_returns()
        self.first_return = self.returns[0]
        self.correct = self.final_reward == 1  # heuristic for accuracy evals
        # Continuous milestone match-rate (matches / total) for partial-credit
        # graders like BFCL multi-turn. With negative_rewards=True the env
        # clamps a 0-score to final_reward=-1, so we recover the underlying
        # match-rate via max(0.0, final_reward). For binary-outcome envs
        # match_rate collapses to int(correct) (0 or 1).
        self.match_rate = max(0.0, float(self.final_reward))

        self.last_state_len = episode_steps[-1].state_len

        # Surface the final step's env metrics (e.g. eval env: task_completion,
        # task_personalization, num_respond_user) so train.py can log them. Exposed
        # as attributes too, so getattr(trajectory, key) in the metric loop works.
        self.metrics: dict[str, float] = dict(episode_steps[-1].metrics or {})
        for _mk, _mv in self.metrics.items():
            if not hasattr(self, _mk):
                setattr(self, _mk, _mv)

    def __len__(self) -> int:
        return len(self.episode_steps)

    def compute_returns(self) -> list[float]:
        """
        Compute returns for each episode step
        """
        if self.episode_steps[-1].return_is_computed:
            all_returns = [step.return_ for step in self.episode_steps]
            all_computed = [step.return_is_computed for step in self.episode_steps]
            not_computed_indices = [_idx for _idx, _comp in enumerate(all_computed) if not _comp]
            assert all(all_computed), (
                f"Not all returns are computed! Returns: {all_returns}\n(Missing indices: {not_computed_indices})"
            )
            return all_returns

        # Otherwise, compute the (discounted) returns
        returns: list[float] = compute_returns_with_last_value(
            rewards=[step.reward for step in self.episode_steps],
            discount_factor=self.discount_factor,
            dones=[step.done for step in self.episode_steps],
            last_value=self.last_value,
        )

        # (Also populate episode_step.final_outcome)
        # -> full_state is a concatenation of prior messages + current state,
        #    so this should also be the trajectory-to-go messages
        last_step = self.episode_steps[-1]
        final_outcome: list[dict[str, str]] = last_step.full_state + [last_step.action] + last_step.next_obs
        last_state_act_obs: list[dict[str, str]] = last_step.state + [last_step.action] + last_step.next_obs  # different if we summarize state
        
        for _idx, return_ in enumerate(returns):
            self.episode_steps[_idx].return_ = return_
            self.episode_steps[_idx].return_is_computed = True
            # Make final outcome messages start at next_obs, i.e., prefix on (state, action)
            _num_prior_messages = len(self.episode_steps[_idx].full_state) + 1  # state + action
            self.episode_steps[_idx].final_outcome = final_outcome[_num_prior_messages:]
            self.episode_steps[_idx].state_returns = returns[:_idx + 1]
            self.episode_steps[_idx].last_state_act_obs = last_state_act_obs
            self.episode_steps[_idx].trajectory_returns = returns

        return returns


class TrajectoryGroup:
    """
    Batch of Trajectories, generated by a group of rollouts
    """

    def __init__(
        self,
        trajectories: list[Trajectory],
        discount_factor: float | None = None,
        final_rewards: list[float] | None = None,
    ) -> None:
        self.trajectories = trajectories
        self.discount_factor = discount_factor
        self.final_rewards = final_rewards or [trajectory.final_reward for trajectory in self.trajectories]
        
        if self.discount_factor is None:
            # Use discount factor from trajectories, but assert they're all the same
            _discount_factor = self.trajectories[0].discount_factor
            assert all(traj.discount_factor == _discount_factor for traj in self.trajectories), (
                f"Discount factors are not all the same: {[traj.discount_factor for traj in self.trajectories]}"
            )
            self.discount_factor = _discount_factor
        
        self.first_returns = self.get_first_returns()
        # self.advantages = self.compute_advantages()  # Explicitly compute these in the generator loop

    def get_first_returns(self) -> list[float]:
        """
        Get the first returns for each trajectory, i.e.,
        the discounted sum of rewards at each step of the trajectory
        """
        return [trajectory.first_return for trajectory in self.trajectories]

    def check_advantages(self) -> list[list[float]] | None:
        """
        Check for and return already-computed advantages in the group
        """
        # Check by considering last trajectory's last step
        if self.trajectories[-1].episode_steps[-1].advantage_is_computed:
            # Now check that all steps have computed advantages
            all_advantages = [[step.advantage for step in trajectory.episode_steps] for trajectory in self.trajectories]
            all_computed = [
                [step.advantage_is_computed for step in trajectory.episode_steps] for trajectory in self.trajectories
            ]
            for traj_idx, traj_advantages in enumerate(all_advantages):
                _not_computed_indices = [_idx for _idx, _comp in enumerate(all_computed[traj_idx]) if not _comp]
                assert len(_not_computed_indices) == 0, (
                    f"Not all advantages are computed for trajectory {traj_idx}!\n"
                    f"Advantages: {traj_advantages}\n(Missing indices: {_not_computed_indices})"
                )
            return all_advantages
        return None

    def compute_advantages(self) -> list[list[float]]:
        """
        Compute advantages for each episode step in the trajectory
        - By default, just use the returns as advantages
        """
        # Return advantages if they're already computed
        maybe_advantages = self.check_advantages()
        if maybe_advantages is not None:
            return maybe_advantages

        advantages = [trajectory.compute_returns() for trajectory in self.trajectories]
        for t_idx, trajectory in enumerate(self.trajectories):
            for e_idx, _ in enumerate(trajectory.episode_steps):
                self.trajectories[t_idx].episode_steps[e_idx].advantage = advantages[t_idx][e_idx]
                self.trajectories[t_idx].episode_steps[e_idx].advantage_is_computed = True
                self.trajectories[t_idx].episode_steps[e_idx].state_advantages = advantages[t_idx][:e_idx + 1]
                self.trajectories[t_idx].episode_steps[e_idx].trajectory_advantages = advantages[t_idx]
        return advantages


class MeanCenteredTrajectoryGroup(TrajectoryGroup):
    """
    Batch of Trajectories, where we compute advantages by mean-centering the final rewards, i.e.,
    advantages = final_rewards - mean(final_rewards)

    If `discount_factor` < 1, we we compute step-wise advantages by applying step-wise discounting
    *after* mean-centering the final returns (as an empirical hack to not having all MC rollouts
    per state at each timestep)
    """

    def compute_advantages(self) -> list[list[float]]:
        """
        Compute advantages for each episode step in the trajectory as (discounted) mean-centered
        final returns
        """
        # Return advantages if they're already computed
        maybe_advantages = self.check_advantages()
        if maybe_advantages is not None:
            return maybe_advantages

        # final_rewards_in_group: list[float] = [
        #     trajectory.final_reward for trajectory in self.trajectories_G
        # ]
        mean_reward: float = sum(self.final_rewards) / len(self.final_rewards)
        if self.discount_factor == 1:  # no discounting, advantage per rollout same for all steps
            advantages: list[list[float]] = [
                [(trajectory.final_reward - mean_reward) for _ in range(len(trajectory))]
                for trajectory in self.trajectories
            ]
        else:
            # Apply step-wise discounting after mean-centering
            advantages = [
                [
                    (traj.final_reward - mean_reward) * (self.discount_factor ** (len(traj) - t - 1))
                    for t in range(len(traj))
                ]
                for traj in self.trajectories
            ]
        for t_idx, trajectory in enumerate(self.trajectories):
            for e_idx, _ in enumerate(trajectory.episode_steps):
                self.trajectories[t_idx].episode_steps[e_idx].advantage = advantages[t_idx][e_idx]
                self.trajectories[t_idx].episode_steps[e_idx].advantage_is_computed = True
        return advantages
