#!/usr/bin/env bash
# Multi-model retail orchestrator (Qwen3-4B then Qwen3-8B). Sequential, resumable,
# self-gating on the GPU (each sub-step waits for main_pytorch to be free). BUILD does
# EM (8B only) + relabel + SFT matrix per model, then a cross-model comparison note.
# Stage-3 (RL) is DEFERRED (needs the rl_eval->tau2 task-index map) — NOT run here.
#
#   1) 4B: relabel + SFT sweep     (EM for 4B already done -> run_em NOT needed)
#   2) 8B: EM (both scorers) -> relabel + SFT sweep
#   3) analyze_sft.py for both models -> notes/cc-5.0-retail_model_compare.md
#   4) print a Stage-3 DEFERRED line (no RL launched)
#
# Usage:  CUDA_VISIBLE_DEVICES=0 nohup ./scripts/run_retail_master.sh > /tmp/aprm/retail_master.log 2>&1 &
set -uo pipefail
cd "$(dirname "$0")/.."
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:/usr/local/bin:$PATH"

ENVCFG=act_prm/tau2_retail
M4B=hf_qwen3_4b_instruct
M8B=hf_qwen3_8b
L=/tmp/aprm/retail_master.log; mkdir -p /tmp/aprm
log(){ echo "[$(date '+%m-%d %H:%M:%S')] $*" | tee -a "$L"; }

log "=== retail MASTER start (GPU ${CUDA_VISIBLE_DEVICES:-?}) : models=[$M4B, $M8B] ==="

# 1) 4B — EM already done; relabel(best+last) + export + SFT matrix only.
log "STEP 1: 4B relabel + SFT sweep ($M4B)"
MODEL_CFG=$M4B ./scripts/run_retail_sweep.sh "$ENVCFG" \
  || log "STEP 1 (4B sweep) returned nonzero (continuing)"

# 2) 8B — Stage-1 EM (both scorers), then relabel + SFT matrix.
log "STEP 2a: 8B Stage-1 EM ($M8B)"
MODEL_CFG=$M8B ./scripts/run_em.sh "$ENVCFG" \
  || log "STEP 2a (8B EM) returned nonzero (continuing)"
log "STEP 2b: 8B relabel + SFT sweep ($M8B)"
MODEL_CFG=$M8B ./scripts/run_retail_sweep.sh "$ENVCFG" \
  || log "STEP 2b (8B sweep) returned nonzero (continuing)"

# 3) Compare: refresh each model's SFT summary, then build the cross-model note.
log "STEP 3: analyze_sft (both models) + cc-5.0 comparison note"
for M in "$M4B" "$M8B"; do
  MODEL_CFG="$M" uv run --no-sync python scripts/analyze_sft.py "$ENVCFG" >> "$L" 2>&1 \
    || log "analyze_sft failed for $M"
done

uv run --no-sync python - <<'PY' >> "$L" 2>&1 || log "compare note failed"
import csv
from pathlib import Path

ENVCFG = "act_prm/tau2_retail"
ENVDIR = ENVCFG.replace("/", "_")
DOM = ENVCFG.split("/")[-1].replace("tau2_", "")
MODELS = ["hf_qwen3_4b_instruct", "hf_qwen3_8b"]


def load(model):
    p = Path("logs") / ENVDIR / model / f"{DOM}_sft_summary.csv"
    if not p.exists():
        return None
    rows = []
    with open(p, newline="") as f:
        for r in csv.DictReader(f):
            try:
                r["ppl"] = float(r["best_eval_action_ppl"])
            except (TypeError, ValueError, KeyError):
                r["ppl"] = None
            v = r.get("variant", "")
            r["corpus"] = "last" if v.endswith("_last") else "best"
            r["base_variant"] = v[:-5] if v.endswith("_last") else v
            rows.append(r)
    return rows


def fmt(x):
    return f"{x:.4f}" if isinstance(x, (int, float)) else "—"


data = {m: load(m) for m in MODELS}
present = [m for m in MODELS if data[m]]

lines = [
    f"# cc-5.0 — {ENVCFG} multi-model SFT comparison",
    "",
    "Auto-generated by `scripts/run_retail_master.sh`. Best eval action-PPL (lower = better",
    "next-action fit) per (model x variant x regime x corpus best/last), read from each",
    "model's `logs/act_prm_tau2_retail/<model>/retail_sft_summary.csv`.",
    "",
]
if not present:
    lines += ["_No per-model summary CSVs found yet (run the sweeps + analyze_sft first)._"]
else:
    lines += [
        "| model | base variant | corpus | regime | best eval action-PPL |",
        "|---|---|---|---|---|",
    ]
    for m in MODELS:
        rows = data[m]
        if not rows:
            lines.append(f"| {m} | (no CSV) | — | — | — |")
            continue
        for r in sorted(rows, key=lambda r: (r["base_variant"], r["corpus"], r["regime"])):
            lines.append(
                f"| {m} | {r['base_variant']} | {r['corpus']} | {r['regime']} | {fmt(r['ppl'])} |"
            )

    lines += ["", "## Thought arms vs each model's own actions_only baseline", ""]
    lines += ["| model | best actions_only PPL | best thoughts_* PPL | lift (ao - thoughts) | thoughts win? |",
              "|---|---|---|---|---|"]
    winners = {}
    for m in MODELS:
        rows = data[m]
        if not rows:
            lines.append(f"| {m} | — | — | — | (no data) |")
            continue
        ao = [r["ppl"] for r in rows if r["base_variant"] == "actions_only" and r["ppl"] is not None]
        th = [r["ppl"] for r in rows if r["base_variant"].startswith("thoughts_") and r["ppl"] is not None]
        ao_best = min(ao) if ao else None
        th_best = min(th) if th else None
        lift = (ao_best - th_best) if (ao_best is not None and th_best is not None) else None
        win = "yes" if (lift is not None and lift > 0) else ("no" if lift is not None else "—")
        if th_best is not None:
            winners[m] = th_best
        lines.append(f"| {m} | {fmt(ao_best)} | {fmt(th_best)} | {fmt(lift)} | {win} |")

    lines += ["", "## Verdict", ""]
    if winners:
        best_model = min(winners, key=winners.get)
        lines.append(
            f"On the inferred-thought arms, **{best_model}** achieves the lowest thoughts_* eval "
            f"action-PPL ({fmt(winners[best_model])})."
        )
        for m in MODELS:
            if m in winners:
                rows = data[m]
                ao = [r["ppl"] for r in rows if r["base_variant"] == "actions_only" and r["ppl"] is not None]
                ao_best = min(ao) if ao else None
                verdict = ("beat" if (ao_best is not None and winners[m] < ao_best) else "did NOT beat")
                lines.append(f"- {m}: thoughts_* {verdict} its own actions_only baseline.")
    else:
        lines.append("_No thought arms found to compare._")

out = Path("notes") / f"cc-5.0-{DOM}_model_compare.md"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines) + "\n")
print("\n".join(lines))
print(f"\nwrote {out}")
PY

log "STEP 3: snapshotting comparison"
./scripts/snapshot.sh "cc-5.0 retail multi-model SFT comparison (4B vs 8B) + per-model summaries" \
  >> "$L" 2>&1 || log "snapshot returned nonzero"

# 4) Stage-3 (RL) is deferred — determine the winner for the log line from cc-5.0 data.
WINNER=$(uv run --no-sync python - <<'PY' 2>/dev/null
import csv
from pathlib import Path
DOM = "retail"; ENVDIR = "act_prm_tau2_retail"
MODELS = ["hf_qwen3_4b_instruct", "hf_qwen3_8b"]
best = {}
for m in MODELS:
    p = Path("logs") / ENVDIR / m / f"{DOM}_sft_summary.csv"
    if not p.exists():
        continue
    vals = []
    with open(p, newline="") as f:
        for r in csv.DictReader(f):
            if r.get("variant", "").startswith("thoughts_"):
                try:
                    vals.append(float(r["best_eval_action_ppl"]))
                except (TypeError, ValueError):
                    pass
    if vals:
        best[m] = min(vals)
print(min(best, key=best.get) if best else "unknown")
PY
)
WINNER="${WINNER:-unknown}"

log "STAGE 3 (RL) DEFERRED — needs rl_eval->tau2 task-index map (user). Winner=$WINNER; run winner first when unblocked."
# Example (do NOT run until the rl_eval->tau2 map is wired):
#   MODEL_CFG=$WINNER ./scripts/run_retail_stage3.sh
log "=== retail MASTER done ==="
